routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/welcome');
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [
    App\Http\Controllers\HomeController::class, 'index'
])->middleware(['checkrole:admin,petugas,siswa'])->name('home');

// Route::get('/home', function () {
//     return view('home');
// })->name('home')->middleware(['checkrole:admin,petugas,siswa']);

Route::group(['prefix' => 'user', 'as' => 'user.'], function () {

    Route::group(['middleware' => 'checkrole:admin'], function () {
        Route::get('/', [
            App\Http\Controllers\UserController::class, 'index'
        ])->name('index');

        Route::get('/create', [
            App\Http\Controllers\UserController::class, 'create'
        ])->name('create');

        Route::post('/store', [
            App\Http\Controllers\UserController::class, 'store'
        ])->name('store');

        Route::get('/edit/{id}', [
            App\Http\Controllers\UserController::class, 'edit'
        ])->name('edit');

        Route::put('/{id}', [
            App\Http\Controllers\UserController::class, 'update'
        ])->name('update');

        Route::get('/show/{id}', [
            App\Http\Controllers\UserController::class, 'show'
        ])->name('show');

        Route::delete('/{id}', [
            App\Http\Controllers\UserController::class, 'destroy'
        ])->name('delete');
    });
});


Route::group(['prefix' => 'siswa', 'as' => 'siswa.'], function () {
    // Route::get('/login', App\Http\Controllers\SiswaLoginController::class, 'login')->name('login');

    Route::get('/login', [
        'uses' => 'App\Http\Controllers\SiswaLoginController@index',
        'as' => 'login'
    ]);

    Route::post('/action-login', [
        'uses' => 'App\Http\Controllers\SiswaLoginController@actionlogin',
        'as' => 'action-login'
    ]);

    Route::get('/histori', [
        'uses' => 'App\Http\Controllers\historiController@index',
        'as' => 'histori'
    ])->middleware('checkrole:admin,petugas,siswa');

    // Route::middleware('middleware' => 'checkrole:admin')
    Route::group(['middleware' => 'checkrole:admin'], function () {
        Route::get('/', [
            App\Http\Controllers\SiswaController::class, 'index'
        ])->name('index');

        Route::get('/create', [
            App\Http\Controllers\SiswaController::class, 'create'
        ])->name('create');

        Route::post('/store', [
            App\Http\Controllers\SiswaController::class, 'store'
        ])->name('store');

        Route::get('/edit/{id}', [
            App\Http\Controllers\SiswaController::class, 'edit'
        ])->name('edit');

        Route::put('/{id}', [
            App\Http\Controllers\SiswaController::class, 'update'
        ])->name('update');

        Route::get('/show/{id}', [
            App\Http\Controllers\SiswaController::class, 'show'
        ])->name('show');

        Route::delete('/{id}', [
            App\Http\Controllers\SiswaController::class, 'destroy'
        ])->name('delete');
    });
});

Route::group(['prefix' => 'kelas', 'as' => 'kelas.'], function () {

    Route::group(['middleware' => 'checkrole:admin'], function () {
        Route::get('/', [
            App\Http\Controllers\KelasController::class, 'index'
        ])->name('index');

        Route::get('/create', [
            App\Http\Controllers\KelasController::class, 'create'
        ])->name('create');

        Route::post('/store', [
            App\Http\Controllers\KelasController::class, 'store'
        ])->name('store');

        Route::get('/edit/{id}', [
            App\Http\Controllers\KelasController::class, 'edit'
        ])->name('edit');

        Route::put('/{id}', [
            App\Http\Controllers\KelasController::class, 'update'
        ])->name('update');

        Route::get('/show/{id}', [
            App\Http\Controllers\KelasController::class, 'show'
        ])->name('show');

        Route::delete('/{id}', [
            App\Http\Controllers\KelasController::class, 'destroy'
        ])->name('delete');
    });
});

Route::group(['prefix' => 'spp', 'as' => 'spp.'], function () {

    Route::group(['middleware' => 'checkrole:admin'], function () {
        Route::get('/', [
            App\Http\Controllers\SppController::class, 'index'
        ])->name('index');

        Route::get('/create', [
            App\Http\Controllers\SppController::class, 'create'
        ])->name('create');

        Route::post('/store', [
            App\Http\Controllers\SppController::class, 'store'
        ])->name('store');

        Route::get('/edit/{id}', [
            App\Http\Controllers\SppController::class, 'edit'
        ])->name('edit');

        Route::put('/{id}', [
            App\Http\Controllers\SppController::class, 'update'
        ])->name('update');

        Route::get('/show/{id}', [
            App\Http\Controllers\SppController::class, 'show'
        ])->name('show');

        Route::delete('/{id}', [
            App\Http\Controllers\SppController::class, 'destroy'
        ])->name('delete');
    });
});

Route::group(['prefix' => 'pembayaran', 'as' => 'pembayaran.'], function () {

    Route::group(['middleware' => 'checkrole:admin'], function () {
        Route::get('/', [
            App\Http\Controllers\PembayaranController::class, 'index'
        ])->name('index');

        Route::get('/create', [
            App\Http\Controllers\PembayaranController::class, 'create'
        ])->name('create');

        Route::post('/store', [
            App\Http\Controllers\PembayaranController::class, 'store'
        ])->name('store');

        Route::get('/edit/{id}', [
            App\Http\Controllers\PembayaranController::class, 'edit'
        ])->name('edit');

        Route::put('/{id}', [
            App\Http\Controllers\PembayaranController::class, 'update'
        ])->name('update');

        Route::get('/show/{id}', [
            App\Http\Controllers\PembayaranController::class, 'show'
        ])->name('show');

        Route::delete('/{id}', [
            App\Http\Controllers\PembayaranController::class, 'destroy'
        ])->name('delete');
        // Route::get('/laporan', [
        //     App\Http\Controllers\PembayaranController::class, 'laporan'
        // ])->name('laporan');
        // Route::get('/laporan/{tglawal}/{tglakhir}', [
        //     App\Http\Controllers\PembayaranController::class, 'cetakpdf'
        // ])->name('laporan.cetak');
        
    });
});


Route::get('/histori', [
    App\Http\Controllers\historiController::class, 'index'
])->middleware(['checkrole:admin,petugas'])->name('histori.index');

Route::get('/generate-laporan', [
    App\Http\Controllers\PembayaranController::class, 'generatelaporan'
])->middleware(['checkrole:admin'])->name('laporan.index');
Route::get('/generate-laporan-cetak/{tglawal}/{tglakhir}', [
    App\Http\Controllers\PembayaranController::class, 'generatelaporancetak'
])->middleware(['checkrole:admin'])->name('generate-laporan-cetak');

resources/views/dashboard.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1 class="m-0 text-dark">Dashboard</h1>
@stop
@section('content')
<!-- Small boxes (Stat box) -->
<div class="row">
  <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-info">
      <div class="inner">
        <h3>{{ $siswa->siswa->count() }}</h3>

        <p>Siswa</p>
      </div>
      <div class="icon">
        <i class="fas fa-users"></i>
      </div>
      <a href="{{ route('siswa.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <!-- ./col -->
  <!-- ./col -->
  {{-- <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-danger">
      <div class="inner">
        <h3>{{ $total_kelas }}</h3>

        <p>Kelas</p>
      </div>
      <div class="icon">
        <i class="fas fa-school"></i>
      </div>
      <a href="{{ route('kelas.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div> --}}
  <!-- ./col -->
  {{-- <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-success">
      <div class="inner">
        <h3>{{ $total_petugas }}</h3>

        <p>Petugas</p>
      </div>
      <div class="icon">
        <i class="fas fa-user-tie"></i>
      </div>
      <a href="{{ route('petugas.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div> --}}
  <!-- ./col -->
  {{-- <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-warning">
      <div class="inner">
        <h3>{{ $total_admin }}</h3>

        <p>Admin</p>
      </div>
      <div class="icon">
        <i class="fas fa-user-secret"></i>
      </div>
      <a href="{{ route('admin-list.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>
</div>
<!-- /.row -->

<div class="container mt-5">
    <div class="row">
        <div class="col-md-10 offset-md-1">
            <div class="card">
                <div class="card-header">Siswa</div>
                <div class="card-body">
                    <canvas id="canvas" height="200" width="500"></canvas>
                </div>
            </div>
        </div>
    </div>
</div> --}}
@stop

@push('js')
<script type="text/javascript" src="{{ asset('templates/backend/AdminLTE-3.1.0') }}/plugins/chart.js/Chart.min.js"></script>
<script>
// var ctx = document.getElementById("canvas").getContext('2d');
//   var myChart = new Chart(ctx, {
//     type: 'bar',
//     data: {
//       labels: ["Siswa Laki-laki", "Siswa Perempuan"],
//       datasets: [{
//         label: '',
//         data: [
//         {!! $siswa_laki_laki !!},
//         {!! $siswa_perempuan !!},
//         ],
//         backgroundColor: [
//         'rgba(255, 99, 132, 0.2)',
//         'rgba(54, 162, 235, 0.2)',
//         ],
//         borderColor: [
//         'rgba(255,99,132,1)',
//         'rgba(54, 162, 235, 1)',
//         ],
//         borderWidth: 1
//       }]
//     },
//     options: {
//       scales: {
//         yAxes: [{
//           ticks: {
//             beginAtZero:true
//           }
//         }]
//       }
//     }
//   });
</script>
@endpush

resources/views/home.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1 class="m-0 text-dark">Dashboard</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-lg-12 col-12">
            <!-- small box -->
            <div class="small-box bg-info">
                <div class="inner">
                    <h3>Pendapatan</h3>
                    <h3>Rp. {{ $totalpendapatan }}</h3>
                </div>
                <div class="icon">
                    <i class="ion ion-pie-graph"></i>
                </div>
                <a href="{{ route('histori.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <div class="col-lg-4 col-6">
            <!-- small box -->
            <div class="small-box bg-danger">
                <div class="inner">

                    <h3 class="num" data-val="{{ $siswa }}">0</h3>
                    <p>SISWA</p>
                </div>
                <div class="icon">
                    <i class="ion ion-bag"></i>
                </div>
                <a href="{{ route('siswa.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-4 col-6">
            <!-- small box -->
            <div class="small-box bg-warning">
                <div class="inner">
                    <h3 class="num" data-val="{{ $user }}">0</h3>
                    <p>PETUGAS</p>
                </div>
                <div class="icon">
                    <i class="ion ion-stats-bars"></i>
                </div>
                <a href="{{ route('user.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-4 col-6">
            <!-- small box -->
            <div class="small-box bg-success">
                <div class="inner">
                    <h3 class="num" data-val="{{ $kelas }}">0</h3>
                    <p>KELAS</p>
                </div>
                <div class="icon">
                    <i class="ion ion-person-add"></i>
                </div>
                <a href="{{ route('kelas.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->

        <!-- ./col -->

        <script>
            let valueDisplays = document.querySelectorAll(".num");
            let interval = 2000;
            valueDisplays.forEach((valueDisplay) => {
                let startValue = 0;
                let endValue = parseInt(valueDisplay.getAttribute("data-val"));
                let duration = Math.floor(interval / endValue);
                let counter = setInterval(function() {
                    startValue += 1;
                    valueDisplay.textContent = startValue;
                    if (startValue == endValue) {
                        clearInterval(counter);
                    }
                }, duration);
            });

        </script>
    @stop