routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/welcome');
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [
    App\Http\Controllers\HomeController::class, 'index'
])->middleware(['checkrole:admin,petugas,siswa'])->name('home');

// Route::get('/home', function () {
//     return view('home');
// })->name('home')->middleware(['checkrole:admin,petugas,siswa']);

Route::group(['prefix' => 'user', 'as' => 'user.'], function () {

    Route::group(['middleware' => 'checkrole:admin'], function () {
        Route::get('/', [
            App\Http\Controllers\UserController::class, 'index'
        ])->name('index');

        Route::get('/create', [
            App\Http\Controllers\UserController::class, 'create'
        ])->name('create');

        Route::post('/store', [
            App\Http\Controllers\UserController::class, 'store'
        ])->name('store');

        Route::get('/edit/{id}', [
            App\Http\Controllers\UserController::class, 'edit'
        ])->name('edit');

        Route::put('/{id}', [
            App\Http\Controllers\UserController::class, 'update'
        ])->name('update');

        Route::get('/show/{id}', [
            App\Http\Controllers\UserController::class, 'show'
        ])->name('show');

        Route::delete('/{id}', [
            App\Http\Controllers\UserController::class, 'destroy'
        ])->name('delete');
    });
});


Route::group(['prefix' => 'siswa', 'as' => 'siswa.'], function () {
    // Route::get('/login', App\Http\Controllers\SiswaLoginController::class, 'login')->name('login');

    Route::get('/login', [
        'uses' => 'App\Http\Controllers\SiswaLoginController@index',
        'as' => 'login'
    ]);

    Route::post('/action-login', [
        'uses' => 'App\Http\Controllers\SiswaLoginController@actionlogin',
        'as' => 'action-login'
    ]);

    Route::get('/histori', [
        'uses' => 'App\Http\Controllers\historiController@index',
        'as' => 'histori'
    ])->middleware('checkrole:admin,petugas,siswa');

    // Route::middleware('middleware' => 'checkrole:admin')
    Route::group(['middleware' => 'checkrole:admin'], function () {
        Route::get('/', [
            App\Http\Controllers\SiswaController::class, 'index'
        ])->name('index');

        Route::get('/create', [
            App\Http\Controllers\SiswaController::class, 'create'
        ])->name('create');

        Route::post('/store', [
            App\Http\Controllers\SiswaController::class, 'store'
        ])->name('store');

        Route::get('/edit/{id}', [
            App\Http\Controllers\SiswaController::class, 'edit'
        ])->name('edit');

        Route::put('/{id}', [
            App\Http\Controllers\SiswaController::class, 'update'
        ])->name('update');

        Route::get('/show/{id}', [
            App\Http\Controllers\SiswaController::class, 'show'
        ])->name('show');

        Route::delete('/{id}', [
            App\Http\Controllers\SiswaController::class, 'destroy'
        ])->name('delete');
    });
});

Route::group(['prefix' => 'kelas', 'as' => 'kelas.'], function () {

    Route::group(['middleware' => 'checkrole:admin'], function () {
        Route::get('/', [
            App\Http\Controllers\KelasController::class, 'index'
        ])->name('index');

        Route::get('/create', [
            App\Http\Controllers\KelasController::class, 'create'
        ])->name('create');

        Route::post('/store', [
            App\Http\Controllers\KelasController::class, 'store'
        ])->name('store');

        Route::get('/edit/{id}', [
            App\Http\Controllers\KelasController::class, 'edit'
        ])->name('edit');

        Route::put('/{id}', [
            App\Http\Controllers\KelasController::class, 'update'
        ])->name('update');

        Route::get('/show/{id}', [
            App\Http\Controllers\KelasController::class, 'show'
        ])->name('show');

        Route::delete('/{id}', [
            App\Http\Controllers\KelasController::class, 'destroy'
        ])->name('delete');
    });
});

Route::group(['prefix' => 'spp', 'as' => 'spp.'], function () {

    Route::group(['middleware' => 'checkrole:admin'], function () {
        Route::get('/', [
            App\Http\Controllers\SppController::class, 'index'
        ])->name('index');

        Route::get('/create', [
            App\Http\Controllers\SppController::class, 'create'
        ])->name('create');

        Route::post('/store', [
            App\Http\Controllers\SppController::class, 'store'
        ])->name('store');

        Route::get('/edit/{id}', [
            App\Http\Controllers\SppController::class, 'edit'
        ])->name('edit');

        Route::put('/{id}', [
            App\Http\Controllers\SppController::class, 'update'
        ])->name('update');

        Route::get('/show/{id}', [
            App\Http\Controllers\SppController::class, 'show'
        ])->name('show');

        Route::delete('/{id}', [
            App\Http\Controllers\SppController::class, 'destroy'
        ])->name('delete');
    });
});

Route::group(['prefix' => 'pembayaran', 'as' => 'pembayaran.'], function () {

    Route::group(['middleware' => 'checkrole:admin'], function () {
        Route::get('/', [
            App\Http\Controllers\PembayaranController::class, 'index'
        ])->name('index');

        Route::get('/create', [
            App\Http\Controllers\PembayaranController::class, 'create'
        ])->name('create');

        Route::post('/store', [
            App\Http\Controllers\PembayaranController::class, 'store'
        ])->name('store');

        Route::get('/edit/{id}', [
            App\Http\Controllers\PembayaranController::class, 'edit'
        ])->name('edit');

        Route::put('/{id}', [
            App\Http\Controllers\PembayaranController::class, 'update'
        ])->name('update');

        Route::get('/show/{id}', [
            App\Http\Controllers\PembayaranController::class, 'show'
        ])->name('show');

        Route::delete('/{id}', [
            App\Http\Controllers\PembayaranController::class, 'destroy'
        ])->name('delete');
        // Route::get('/laporan', [
        //     App\Http\Controllers\PembayaranController::class, 'laporan'
        // ])->name('laporan');
        // Route::get('/laporan/{tglawal}/{tglakhir}', [
        //     App\Http\Controllers\PembayaranController::class, 'cetakpdf'
        // ])->name('laporan.cetak');
        
    });
});


Route::get('/histori', [
    App\Http\Controllers\historiController::class, 'index'
])->middleware(['checkrole:admin,petugas'])->name('histori.index');

Route::get('/generate-laporan', [
    App\Http\Controllers\PembayaranController::class, 'generatelaporan'
])->middleware(['checkrole:admin'])->name('laporan.index');
Route::get('/generate-laporan-cetak/{tglawal}/{tglakhir}', [
    App\Http\Controllers\PembayaranController::class, 'generatelaporancetak'
])->middleware(['checkrole:admin'])->name('generate-laporan-cetak');

app/Models/Pembayaran.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pembayaran extends Model
{
    use HasFactory;
    
    protected $table = 'pembayaran';

    protected $fillable = [
        'id_user',
        'id_siswa', 
        'spp_bulan', 
        'jumlah_bayar'
    ];


    protected $hidden = [];

    public function siswa()
   {
       return $this->belongsTo(Siswa::class, 'id_siswa', 'id');
   }

   public function user()
   {
       return $this->belongsTo(User::class, 'id_user', 'id', 'nisn' ); 
   }
}

app/Http/Controllers/pembayaranController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pembayaran;
use App\Models\Siswa;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class pembayaranController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $totalpendapatan = DB::table('jumlah_bayar')->get();
        $pembayaran = Pembayaran::with('user', 'siswa')->get();
        return view('layouts.pembayaran.index', compact('pembayaran',));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $siswa = Siswa::all();
        $user = User::all();
        return view('layouts.pembayaran.create', compact('user', 'siswa'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nisn' => ['required', 'numeric'],
            'spp_bulan' => ['required'],
            'jumlah_bayar' => ['required', 'numeric'],
        ]);

        DB::beginTransaction();
        try {
            // dd($request->all());
            $nisn = $request->nisn;
            $siswa = Siswa::whereNisn($nisn)->first();
            $user = new Pembayaran();
            $user->id_user = Auth::id();
            $user->id_siswa = $siswa->id;
            $user->spp_bulan = $request->spp_bulan;
            $user->jumlah_bayar = $request->jumlah_bayar;
            $user->save();

            DB::commit();
        } catch (\Exception $e) {
            DB::rollBack();
            return redirect()->back()->withErrors(['Data Pembayaran gagal disimpan'])->withInput();
        }
        return redirect('pembayaran')->with('status', 'Data Pembayaran berhasil di simpan.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pembayaran = Pembayaran::find($id);
        $siswa = Siswa::all();
        $user = User::all();
        return view('layouts.pembayaran.edit', [
            'pembayaran' => $pembayaran,
            'siswa' => $siswa,
            'user' => $user,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nisn' => ['required', 'numeric'], //cba kamu cek lgi cek apanya
            'spp_bulan' => ['required'],
            'jumlah_bayar' => ['required', 'numeric'],
        ]);

        try {
            // dd($request->all());
            $nisn = $request->nisn;
            $siswa = Siswa::whereNisn($nisn)->first();
            $user = Pembayaran::find($id);
            $user->id_user = Auth::id();
            $user->id_siswa = $siswa->id;
            $user->spp_bulan = $request->spp_bulan;
            $user->jumlah_bayar = $request->jumlah_bayar;
            $user->save();
        } catch (\Exception $e) {
            return redirect()->back()->withErrors(['Data Siswa gagal disimpan'])->withInput();
        }
        return redirect('pembayaran')->with('status', 'Data Siswa berhasil di simpan.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function generatelaporan()
    {
        return view('layouts.laporan.index');
    }
    public function generatelaporancetak($tglawal, $tglakhir)
    {
        // dd(["Tanggal Awal : ".$tglawal, "Tanggal Akhir : ".$tglakhir]);
        $pembayaran = Pembayaran::with('siswa')->whereBetween('created_at',[$tglawal, $tglakhir])->oldest()->get();
        $totalpendapatan = Pembayaran::sum('jumlah_bayar');
        return view('layouts.laporan.generate-laporan-cetak', compact('pembayaran','totalpendapatan','tglawal','tglakhir'));
    }

}

resources/views/layouts/pembayaran/create.blade.php
@extends('adminlte::page')
@section('title', 'Halaman Tambah Pembayaran')
@section('content_header')
    <h1>Tambah Pembayaran</h1>
@stop
@section('link')
    <li class="breadcrumb-item"><a href="{{ route('pembayaran.index') }}">Pembayaran</a></li>
    <li class="breadcrumb-item active">Tambah</li>
@stop
@section('content')
    <div class="card">
        <div class="card-body">
            @if ($errors->any())
                <x-adminlte-alert theme="danger" title="Kesalahan">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </x-adminlte-alert>
            @endif
            <form method="POST" action="{{ route('pembayaran.store') }}">
                @csrf
                <div class="row mb-3">
                    <label for="nisn" class="col-md-4 col-form-label text-mdend">{{ __('NISN Siswa') }}</label>
                    <div class="col-md-6">
                        <input id="nisn" type="text" class="form-control @error('nisn') is-invalid @enderror"
                            name="nisn" value="{{ old('nisn') }}" required autocomplete="nisn" autofocus>
                        @error('nisn')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="spp_bulan" class="col-md-4 col-form-label textmd-end">{{ __('SPP Bulan') }}</label>
                    <div class="col-md-6">
                        <select id="spp_bulan" class="form-control @error('spp_bulan') is-invalid @enderror" 
                        name="spp_bulan" required>

                        <option value="">Silahkan Pilih</option>											
                        <option value="januari">Januari</option>
                        <option value="februari">Februari</option>
                        <option value="maret">Maret</option>
                        <option value="april">April</option>
                        <option value="mei">Mei</option>
                        <option value="juni">Juni</option>
                        <option value="juli">Juli</option>
                        <option value="agustus">Agustus</option>
                        <option value="september">September</option>
                        <option value="oktober">Oktober</option>
                        <option value="november">November</option>
                        <option value="desember">Desember</option>
                            
                        </select>
                        @error('spp_bulan')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                

                <div class="row mb-3">
                    <label for="jumlah_bayar" class="col-md-4 col-form-label text-mdend">{{ __('Jumlah Bayar') }}</label>
                    <div class="col-md-6">
                        <input id="jumlah_bayar" type="text" class="form-control @error('jumlah_bayar') is-invalid @enderror"
                            name="jumlah_bayar" value="{{ old('jumlah_bayar') }}" required autofocus>
                        @error('jumlah_bayar')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Simpan
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/layouts/pembayaran/edit.blade.php
@extends('adminlte::page')
@section('title', 'Halaman Tambah Siswa')
@section('content_header')
    <h1>Tambah Siswa</h1>
@stop
@section('link')
    <li class="breadcrumb-item"><a href="{{ route('pembayaran.index') }}">Siswa</a></li>
    <li class="breadcrumb-item active">Tambah</li>
@stop
@section('content')
    <div class="card">
        <div class="card-body">
            @if ($errors->any())
                <x-adminlte-alert theme="danger" title="Kesalahan">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </x-adminlte-alert>
            @endif
            <form method="POST" action="{{ route('pembayaran.update', $pembayaran->id) }}">
                @csrf
                @method('PUT')
                <div class="row mb-3">
                    <label for="nisn" class="col-md-4 col-form-label text-mdend">{{ __('NISN Siswa') }}</label>
                    <div class="col-md-6">
                        <input id="nisn" type="text" class="form-control @error('nisn') is-invalid @enderror"
                            name="nisn" value="{{ $pembayaran->nisn }}" required autocomplete="nisn" autofocus>
                        @error('nisn')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="spp_bulan" class="col-md-4 col-form-label textmd-end">{{ __('SPP Bulan') }}</label>
                    <div class="col-md-6">
                        <select id="spp_bulan" class="form-control @error('spp_bulan') is-invalid @enderror" 
                        name="spp_bulan" required>

                        <option value="">Silahkan Pilih</option>											
                        <option value="januari">Januari</option>
                        <option value="februari">Februari</option>
                        <option value="maret">Maret</option>
                        <option value="april">April</option>
                        <option value="mei">Mei</option>
                        <option value="juni">Juni</option>
                        <option value="juli">Juli</option>
                        <option value="agustus">Agustus</option>
                        <option value="september">September</option>
                        <option value="oktober">Oktober</option>
                        <option value="november">November</option>
                        <option value="desember">Desember</option>
                            
                        </select>
                        @error('spp_bulan')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                

                <div class="row mb-3">
                    <label for="jumlah_bayar" class="col-md-4 col-form-label text-mdend">{{ __('Jumlah Bayar') }}</label>
                    <div class="col-md-6">
                        <input id="jumlah_bayar" type="text" class="form-control @error('jumlah_bayar') is-invalid @enderror"
                            name="jumlah_bayar" value="{{ $pembayaran->jumlah_bayar }}" required autofocus>
                        @error('jumlah_bayar')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Simpan
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/layouts/pembayaran/index.blade.php
@extends('adminlte::page')
@section('title', 'Halaman Siswa')

@section('content_header')
    <h1 class="m-0 text-dark">Pembayaran</h1>
@stop
@section('link')
    <li class="breadcrumb-item active">Pembayaran</li>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            @if (session('status'))
                <x-adminlte-alert theme="success" title="Sukses">
                    {{ session('status') }}
                </x-adminlte-alert>
            @endif
            @if ($errors->any())
                <x-adminlte-alert theme="success" title="Sukses">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </x-adminlte-alert>
            @endif
            <a href="{{ route('pembayaran.create') }}" class="btn btn-md btn-success mx-1 shadow"> <i
                    class="fa fa-lg fa-fw fa-plus"></i> Tambah Pembayaran</a>
            <br /> <br />
            <div class="table-responsive">
                <table id="tabel_user" class="table table-striped table-hover table-condensed table-bordered">
                    <thead>
                        <tr style="background-color: darkgrey">
                            <th>No</th>
                            <th>Petugas </th>
                            <th>NISN Siswa</th>
                            <th>Nama Siswa</th>
                            <th>SPP</th>
                            <th>Jumlah Bayar</th>
                            <th>Tanggal Bayar</th>
                            <th class="text-center" width="100">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($pembayaran as $p)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $p->user->name }}</td>
                                <td>{{ $p->siswa->nisn }}</td>
                                <td>{{ $p->siswa->nama }}</td>
                                <td>{{ $p->siswa->spp->nominal }}</td>
                                <td>{{ $p->jumlah_bayar }}</td>
                                <td>{{ $p->created_at->format('d M Y') }}</td>
                                <td>
                                    <a href="{{route('pembayaran.edit',$p->id)}}" class="btn btn-sn btn-primary"
                                        title="Edit"><i class="far fa-edit"></i></a>
                                        <x-adminlte-button class="btn btn-sn btn-danger"  data-toggle="modal" data-target="#hapussiswa{{$loop->iteration}}" icon="far fa-trash-alt" class="bg-danger"> </x-adminlte-button>
                                            {{-- Custom --}}
                                        <x-adminlte-modal id="hapussiswa{{$loop->iteration}}" title="Hapus Siswa" size="md" theme="danger"
                                        icon="fas fa-bell" v-centered static-backdrop scrollable>
                                        <div style="height:80px;">
                                            <form action="{{route('pembayaran.delete',$p->id)}}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                  Apakah anda yakin akan menghapus siswa ini?</div>
                                        <x-slot name="footerSlot">
                                            <x-adminlte-button type="submit" class="mr-auto" theme="primary" label="Hapus"/>
                                            <x-adminlte-button theme="danger" label="Batal" data-dismiss="modal"/>
                                            </form>
                                        </x-slot>
                                        </x-adminlte-modal>
                                </td>



                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>


@stop
@section('plugins.Datatables', true)
@section('js')
    <script>
        $('#tabel_siswa').DataTable();
    </script>
@stop