routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/welcome');
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [
    App\Http\Controllers\HomeController::class, 'index'
])->middleware(['checkrole:admin,petugas,siswa'])->name('home');

// Route::get('/home', function () {
//     return view('home');
// })->name('home')->middleware(['checkrole:admin,petugas,siswa']);

Route::group(['prefix' => 'user', 'as' => 'user.'], function () {

    Route::group(['middleware' => 'checkrole:admin'], function () {
        Route::get('/', [
            App\Http\Controllers\UserController::class, 'index'
        ])->name('index');

        Route::get('/create', [
            App\Http\Controllers\UserController::class, 'create'
        ])->name('create');

        Route::post('/store', [
            App\Http\Controllers\UserController::class, 'store'
        ])->name('store');

        Route::get('/edit/{id}', [
            App\Http\Controllers\UserController::class, 'edit'
        ])->name('edit');

        Route::put('/{id}', [
            App\Http\Controllers\UserController::class, 'update'
        ])->name('update');

        Route::get('/show/{id}', [
            App\Http\Controllers\UserController::class, 'show'
        ])->name('show');

        Route::delete('/{id}', [
            App\Http\Controllers\UserController::class, 'destroy'
        ])->name('delete');
    });
});


Route::group(['prefix' => 'siswa', 'as' => 'siswa.'], function () {
    // Route::get('/login', App\Http\Controllers\SiswaLoginController::class, 'login')->name('login');

    Route::get('/login', [
        'uses' => 'App\Http\Controllers\SiswaLoginController@index',
        'as' => 'login'
    ]);

    Route::post('/action-login', [
        'uses' => 'App\Http\Controllers\SiswaLoginController@actionlogin',
        'as' => 'action-login'
    ]);

    Route::get('/histori', [
        'uses' => 'App\Http\Controllers\historiController@index',
        'as' => 'histori'
    ])->middleware('checkrole:admin,petugas,siswa');

    // Route::middleware('middleware' => 'checkrole:admin')
    Route::group(['middleware' => 'checkrole:admin'], function () {
        Route::get('/', [
            App\Http\Controllers\SiswaController::class, 'index'
        ])->name('index');

        Route::get('/create', [
            App\Http\Controllers\SiswaController::class, 'create'
        ])->name('create');

        Route::post('/store', [
            App\Http\Controllers\SiswaController::class, 'store'
        ])->name('store');

        Route::get('/edit/{id}', [
            App\Http\Controllers\SiswaController::class, 'edit'
        ])->name('edit');

        Route::put('/{id}', [
            App\Http\Controllers\SiswaController::class, 'update'
        ])->name('update');

        Route::get('/show/{id}', [
            App\Http\Controllers\SiswaController::class, 'show'
        ])->name('show');

        Route::delete('/{id}', [
            App\Http\Controllers\SiswaController::class, 'destroy'
        ])->name('delete');
    });
});

Route::group(['prefix' => 'kelas', 'as' => 'kelas.'], function () {

    Route::group(['middleware' => 'checkrole:admin'], function () {
        Route::get('/', [
            App\Http\Controllers\KelasController::class, 'index'
        ])->name('index');

        Route::get('/create', [
            App\Http\Controllers\KelasController::class, 'create'
        ])->name('create');

        Route::post('/store', [
            App\Http\Controllers\KelasController::class, 'store'
        ])->name('store');

        Route::get('/edit/{id}', [
            App\Http\Controllers\KelasController::class, 'edit'
        ])->name('edit');

        Route::put('/{id}', [
            App\Http\Controllers\KelasController::class, 'update'
        ])->name('update');

        Route::get('/show/{id}', [
            App\Http\Controllers\KelasController::class, 'show'
        ])->name('show');

        Route::delete('/{id}', [
            App\Http\Controllers\KelasController::class, 'destroy'
        ])->name('delete');
    });
});

Route::group(['prefix' => 'spp', 'as' => 'spp.'], function () {

    Route::group(['middleware' => 'checkrole:admin'], function () {
        Route::get('/', [
            App\Http\Controllers\SppController::class, 'index'
        ])->name('index');

        Route::get('/create', [
            App\Http\Controllers\SppController::class, 'create'
        ])->name('create');

        Route::post('/store', [
            App\Http\Controllers\SppController::class, 'store'
        ])->name('store');

        Route::get('/edit/{id}', [
            App\Http\Controllers\SppController::class, 'edit'
        ])->name('edit');

        Route::put('/{id}', [
            App\Http\Controllers\SppController::class, 'update'
        ])->name('update');

        Route::get('/show/{id}', [
            App\Http\Controllers\SppController::class, 'show'
        ])->name('show');

        Route::delete('/{id}', [
            App\Http\Controllers\SppController::class, 'destroy'
        ])->name('delete');
    });
});

Route::group(['prefix' => 'pembayaran', 'as' => 'pembayaran.'], function () {

    Route::group(['middleware' => 'checkrole:admin'], function () {
        Route::get('/', [
            App\Http\Controllers\PembayaranController::class, 'index'
        ])->name('index');

        Route::get('/create', [
            App\Http\Controllers\PembayaranController::class, 'create'
        ])->name('create');

        Route::post('/store', [
            App\Http\Controllers\PembayaranController::class, 'store'
        ])->name('store');

        Route::get('/edit/{id}', [
            App\Http\Controllers\PembayaranController::class, 'edit'
        ])->name('edit');

        Route::put('/{id}', [
            App\Http\Controllers\PembayaranController::class, 'update'
        ])->name('update');

        Route::get('/show/{id}', [
            App\Http\Controllers\PembayaranController::class, 'show'
        ])->name('show');

        Route::delete('/{id}', [
            App\Http\Controllers\PembayaranController::class, 'destroy'
        ])->name('delete');
        // Route::get('/laporan', [
        //     App\Http\Controllers\PembayaranController::class, 'laporan'
        // ])->name('laporan');
        // Route::get('/laporan/{tglawal}/{tglakhir}', [
        //     App\Http\Controllers\PembayaranController::class, 'cetakpdf'
        // ])->name('laporan.cetak');
        
    });
});


Route::get('/histori', [
    App\Http\Controllers\historiController::class, 'index'
])->middleware(['checkrole:admin,petugas'])->name('histori.index');

Route::get('/generate-laporan', [
    App\Http\Controllers\PembayaranController::class, 'generatelaporan'
])->middleware(['checkrole:admin'])->name('laporan.index');
Route::get('/generate-laporan-cetak/{tglawal}/{tglakhir}', [
    App\Http\Controllers\PembayaranController::class, 'generatelaporancetak'
])->middleware(['checkrole:admin'])->name('generate-laporan-cetak');

app/Models/Spp.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Spp extends Model
{
    use HasFactory;
    protected $table = 'spp';

    protected $fillable = [
        'tahun', 
        'nominal'
    ];


    protected $hidden = [];

    public function siswa(){
        return $this->hasMany(Siswa::class, 'id_spp');
    }
}

app/Http/Controllers/sppController.php
<?php

namespace App\Http\Controllers;

use App\Models\Spp;
use Illuminate\Http\Request;

class sppController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $spp = Spp::all();
        return view('layouts.spp.index', compact('spp'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('layouts.spp.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'tahun' => ['required','min:4','max:4'],
            'nominal' => ['required', 'numeric'],
        ]);
         try{
            $user = new Spp();
            $user->tahun = $request->tahun;
            $user->nominal = $request->nominal;
            $user->save();
       }
        catch(\Exception $e ){

            return redirect()->back()->withErrors(['Spp gagal disimpan']);
        }
        return redirect('spp')->with('status','Spp Berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $spp = Spp::find($id);
        return view('layouts.spp.edit', compact('spp'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'tahun' => ['required','min:4','max:4'],
            'nominal' => ['required', 'numeric'],
        ]);
         try{
            $user = Spp::findOrFail($id);
            $user->tahun = $request->tahun;
            $user->nominal = $request->nominal;
            $user->save();
       }
        catch(\Exception $e ){

            return redirect()->back()->withErrors(['Spp gagal disimpan']);
        }
        return redirect('spp')->with('status','Spp Berhasil ditambahkan');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = Spp::find($id);
        $user->delete();
         
         return redirect()->back()->with('status','spp berhasil dihapus');
    }
}

resources/views/layouts/spp/create.blade.php
@extends('adminlte::page')
@section('title', 'Halaman Tambah Spp')
@section('content_header')
   <h1>Tambah Spp</h1>
@stop
@section('link')
<li class="breadcrumb-item"><a href="{{route('spp.index')}}">Spp</a></li>
<li class="breadcrumb-item active">Tambah</li>
@stop
@section('content')
<div class="card">
   <div class="card-body">
    @if ($errors->any())
                <x-adminlte-alert theme="danger" title="Kesalahan">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </x-adminlte-alert>
            @endif
       <form method="POST" action="{{ route('spp.store') }}" >
           @csrf
           <div class="row mb-3">
               <label for="tahun" class="col-md-4 col-form-label text-mdend">{{ __('Tahun') }}</label>
                   <div class="col-md-6">
                       <input id="tahun" type="text" class="form-control @error('tahun') is-invalid @enderror" name="tahun" value="{{old('kelas') }}" required autocomplete="name" autofocus>
                           @error('tahun')
                               <span class="invalid-feedback" role="alert">
                                   <strong>{{ $message }}</strong>
                               </span>
                           @enderror
                   </div>
           </div>
           <div class="row mb-3">
               <label for="nominal" class="col-md-4 col-form-label text-md-end">{{ __('Nominal') }}</label>
                   <div class="col-md-6">
                       <input id="nominal" type="text" class="form-control @error('nominal') is-invalid @enderror" name="nominal" value="{{ old('nominal') }}"required autocomplete="name" autofocus>
                           @error('nominal')
                               <span class="invalid-feedback" role="alert">
                                   <strong>{{ $message }}</strong>
                               </span>
                           @enderror
                   </div>
           </div>
           <div class="row mb-0">
               <div class="col-md-6 offset-md-4">
                   <button type="submit" class="btn btn-primary">
                                   Simpan
                   </button>
           </div>
       </div>
   </form>
   </div>
</div>
@endsection

resources/views/layouts/spp/edit.blade.php
@extends('adminlte::page')
@section('title', 'Halaman Tambah Spp')
@section('content_header')
   <h1>Edit Spp</h1>
@stop
@section('link')
<li class="breadcrumb-item"><a href="{{route('spp.index')}}">Spp</a></li>
<li class="breadcrumb-item active">Edit</li>
@stop
@section('content')
<div class="card">
   <div class="card-body">
    @if ($errors->any())
                <x-adminlte-alert theme="danger" title="Kesalahan">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </x-adminlte-alert>
            @endif
       <form method="POST" action="{{ route('spp.update', $spp->id) }}" >
           @csrf
           @method('PUT')
           <div class="row mb-3">
               <label for="tahun" class="col-md-4 col-form-label text-mdend">{{ __('Tahun') }}</label>
                   <div class="col-md-6">
                       <input id="tahun" type="text" class="form-control @error('tahun') is-invalid @enderror" name="tahun" value="{{ $spp->tahun}}" required autocomplete="name" autofocus>
                           @error('tahun')
                               <span class="invalid-feedback" role="alert">
                                   <strong>{{ $message }}</strong>
                               </span>
                           @enderror
                   </div>
           </div>
           <div class="row mb-3">
               <label for="nominal" class="col-md-4 col-form-label text-md-end">{{ __('Nominal') }}</label>
                   <div class="col-md-6">
                       <input id="nominal" type="text" class="form-control @error('nominal') is-invalid @enderror" name="nominal" value="{{ $spp->nominal}}"required autocomplete="name" autofocus>
                           @error('nominal')
                               <span class="invalid-feedback" role="alert">
                                   <strong>{{ $message }}</strong>
                               </span>
                           @enderror
                   </div>
           </div>
           <div class="row mb-0">
               <div class="col-md-6 offset-md-4">
                   <button type="submit" class="btn btn-primary">
                                   Simpan
                   </button>
           </div>
       </div>
   </form>
   </div>
</div>
@endsection

resources/views/layouts/spp/index.blade.php
@extends('adminlte::page')
@section('title', 'Halaman Spp')

@section('content_header')
   <h1 class="m-0 text-dark">Spp</h1>
@stop
@section('link')
<li class="breadcrumb-item active">Spp</li>
@stop

@section('content')
<div class="card">
   <div class="card-body">
       @if (session('status'))
           <x-adminlte-alert theme="success" title="Sukses">
               {{session('status')}}
           </x-adminlte-alert>
       @endif
       @if ($errors->any())
           <x-adminlte-alert theme="success" title="Sukses">
               <ul>
                   @foreach ($errors->all() as $error)
                       <li>{{ $error }}</li>
                   @endforeach
               </ul>
           </x-adminlte-alert>
       @endif
       <a href="{{route('spp.create')}}" class="btn btn-md btn-success mx-1 shadow"> <i class="fa fa-lg fa-fw fa-plus"></i> Tambah Kelas</a>
       <br/> <br/>
       <div class="table-responsive">
           <table id="tabel_kelas" class="table table-striped table-hover table-condensed table-bordered">
               <thead>
                   <tr style="background-color: darkgrey">
                       <th>No</th>
                       <th>Tahun </th>
                       <th>Nominal</th>
                       <th class="text-center" width="100">Aksi</th>
                   </tr>
               </thead>
               <tbody>
               @foreach($spp as $p)
                   <tr>
                       <td>{{$loop->iteration}}</td>
                       <td>{{$p->tahun}}</td>
                       <td>{{$p->nominal}}</td>
                       <td>
                        <a href="{{route('spp.edit',$p->id)}}" class="btn btn-sn btn-primary"
                            title="Edit"><i class="far fa-edit"></i></a>
                            <x-adminlte-button class="btn btn-sn btn-danger" data-toggle="modal" data-target="#hapusspp{{$loop->iteration}}" icon="far fa-trash-alt" class="bg-danger"> Hapus </x-adminlte-button>
                                {{-- Custom --}}
                            <x-adminlte-modal id="hapusspp{{$loop->iteration}}" title="Hapus Spp" size="md" theme="danger"
                            icon="fas fa-bell" v-centered static-backdrop scrollable>
                            <div style="height:80px;">
                                <form action="{{route('spp.delete',$p->id)}}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                      Apakah anda yakin akan menghapus spp ini?</div>
                            <x-slot name="footerSlot">
                                <x-adminlte-button type="submit" class="mr-auto" theme="primary" label="Hapus"/>
                                <x-adminlte-button theme="danger" label="Batal" data-dismiss="modal"/>
                                </form>
                            </x-slot>
                            </x-adminlte-modal>
                    </td>

                

                         </tr>
                       @endforeach
               </tbody>
           </table>
       </div>
   </div>
</div>


@stop
@section('plugins.Datatables', true)
@section('js')
   <script> $('#tabel_spp').DataTable();</script>
@stop