routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/welcome');
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [
    App\Http\Controllers\HomeController::class, 'index'
])->middleware(['checkrole:admin,petugas,siswa'])->name('home');

// Route::get('/home', function () {
//     return view('home');
// })->name('home')->middleware(['checkrole:admin,petugas,siswa']);

Route::group(['prefix' => 'user', 'as' => 'user.'], function () {

    Route::group(['middleware' => 'checkrole:admin'], function () {
        Route::get('/', [
            App\Http\Controllers\UserController::class, 'index'
        ])->name('index');

        Route::get('/create', [
            App\Http\Controllers\UserController::class, 'create'
        ])->name('create');

        Route::post('/store', [
            App\Http\Controllers\UserController::class, 'store'
        ])->name('store');

        Route::get('/edit/{id}', [
            App\Http\Controllers\UserController::class, 'edit'
        ])->name('edit');

        Route::put('/{id}', [
            App\Http\Controllers\UserController::class, 'update'
        ])->name('update');

        Route::get('/show/{id}', [
            App\Http\Controllers\UserController::class, 'show'
        ])->name('show');

        Route::delete('/{id}', [
            App\Http\Controllers\UserController::class, 'destroy'
        ])->name('delete');
    });
});


Route::group(['prefix' => 'siswa', 'as' => 'siswa.'], function () {
    // Route::get('/login', App\Http\Controllers\SiswaLoginController::class, 'login')->name('login');

    Route::get('/login', [
        'uses' => 'App\Http\Controllers\SiswaLoginController@index',
        'as' => 'login'
    ]);

    Route::post('/action-login', [
        'uses' => 'App\Http\Controllers\SiswaLoginController@actionlogin',
        'as' => 'action-login'
    ]);

    Route::get('/histori', [
        'uses' => 'App\Http\Controllers\historiController@index',
        'as' => 'histori'
    ])->middleware('checkrole:admin,petugas,siswa');

    // Route::middleware('middleware' => 'checkrole:admin')
    Route::group(['middleware' => 'checkrole:admin'], function () {
        Route::get('/', [
            App\Http\Controllers\SiswaController::class, 'index'
        ])->name('index');

        Route::get('/create', [
            App\Http\Controllers\SiswaController::class, 'create'
        ])->name('create');

        Route::post('/store', [
            App\Http\Controllers\SiswaController::class, 'store'
        ])->name('store');

        Route::get('/edit/{id}', [
            App\Http\Controllers\SiswaController::class, 'edit'
        ])->name('edit');

        Route::put('/{id}', [
            App\Http\Controllers\SiswaController::class, 'update'
        ])->name('update');

        Route::get('/show/{id}', [
            App\Http\Controllers\SiswaController::class, 'show'
        ])->name('show');

        Route::delete('/{id}', [
            App\Http\Controllers\SiswaController::class, 'destroy'
        ])->name('delete');
    });
});

Route::group(['prefix' => 'kelas', 'as' => 'kelas.'], function () {

    Route::group(['middleware' => 'checkrole:admin'], function () {
        Route::get('/', [
            App\Http\Controllers\KelasController::class, 'index'
        ])->name('index');

        Route::get('/create', [
            App\Http\Controllers\KelasController::class, 'create'
        ])->name('create');

        Route::post('/store', [
            App\Http\Controllers\KelasController::class, 'store'
        ])->name('store');

        Route::get('/edit/{id}', [
            App\Http\Controllers\KelasController::class, 'edit'
        ])->name('edit');

        Route::put('/{id}', [
            App\Http\Controllers\KelasController::class, 'update'
        ])->name('update');

        Route::get('/show/{id}', [
            App\Http\Controllers\KelasController::class, 'show'
        ])->name('show');

        Route::delete('/{id}', [
            App\Http\Controllers\KelasController::class, 'destroy'
        ])->name('delete');
    });
});

Route::group(['prefix' => 'spp', 'as' => 'spp.'], function () {

    Route::group(['middleware' => 'checkrole:admin'], function () {
        Route::get('/', [
            App\Http\Controllers\SppController::class, 'index'
        ])->name('index');

        Route::get('/create', [
            App\Http\Controllers\SppController::class, 'create'
        ])->name('create');

        Route::post('/store', [
            App\Http\Controllers\SppController::class, 'store'
        ])->name('store');

        Route::get('/edit/{id}', [
            App\Http\Controllers\SppController::class, 'edit'
        ])->name('edit');

        Route::put('/{id}', [
            App\Http\Controllers\SppController::class, 'update'
        ])->name('update');

        Route::get('/show/{id}', [
            App\Http\Controllers\SppController::class, 'show'
        ])->name('show');

        Route::delete('/{id}', [
            App\Http\Controllers\SppController::class, 'destroy'
        ])->name('delete');
    });
});

Route::group(['prefix' => 'pembayaran', 'as' => 'pembayaran.'], function () {

    Route::group(['middleware' => 'checkrole:admin'], function () {
        Route::get('/', [
            App\Http\Controllers\PembayaranController::class, 'index'
        ])->name('index');

        Route::get('/create', [
            App\Http\Controllers\PembayaranController::class, 'create'
        ])->name('create');

        Route::post('/store', [
            App\Http\Controllers\PembayaranController::class, 'store'
        ])->name('store');

        Route::get('/edit/{id}', [
            App\Http\Controllers\PembayaranController::class, 'edit'
        ])->name('edit');

        Route::put('/{id}', [
            App\Http\Controllers\PembayaranController::class, 'update'
        ])->name('update');

        Route::get('/show/{id}', [
            App\Http\Controllers\PembayaranController::class, 'show'
        ])->name('show');

        Route::delete('/{id}', [
            App\Http\Controllers\PembayaranController::class, 'destroy'
        ])->name('delete');
        // Route::get('/laporan', [
        //     App\Http\Controllers\PembayaranController::class, 'laporan'
        // ])->name('laporan');
        // Route::get('/laporan/{tglawal}/{tglakhir}', [
        //     App\Http\Controllers\PembayaranController::class, 'cetakpdf'
        // ])->name('laporan.cetak');
        
    });
});


Route::get('/histori', [
    App\Http\Controllers\historiController::class, 'index'
])->middleware(['checkrole:admin,petugas'])->name('histori.index');

Route::get('/generate-laporan', [
    App\Http\Controllers\PembayaranController::class, 'generatelaporan'
])->middleware(['checkrole:admin'])->name('laporan.index');
Route::get('/generate-laporan-cetak/{tglawal}/{tglakhir}', [
    App\Http\Controllers\PembayaranController::class, 'generatelaporancetak'
])->middleware(['checkrole:admin'])->name('generate-laporan-cetak');

app/Models/Siswa.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Siswa extends Authenticatable
{
    use HasFactory;
    protected $table = 'siswa';
    protected $guard = 'siswa';

    protected $fillable = [
        'nisn',
        'nis',
        'nama',
        'id_kelas',
        'nomor_telp',
        'alamat',
        'id_spp',
    ];


    protected $hidden = [];

    public function kelas()
    {
        return $this->belongsTo(Kelas::class, 'id_kelas', 'id');
    }

    public function spp()
    {
        return $this->belongsTo(Spp::class, 'id_spp', 'id');
    }

    public function pembayaran()
    {
        return $this->hasMany(Pembayaran::class, 'id_siswa');
    }
}

app/Http/Controllers/siswaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kelas;
use App\Models\Siswa;
use App\Models\Spp;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class siswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $siswa = DB::table('siswa')->get();
        // dd($siswa);
        $siswa = Siswa::with('kelas')->get();
        return view('layouts.siswa.index', compact('siswa'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kelas = Kelas::all();
        $spp = Spp::all();
        return view('layouts.siswa.create', [
            'kelas' => $kelas,
            'spp' => $spp
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nisn' => ['required', 'unique:siswa', 'numeric'],
            'nis' => ['required', 'numeric'],
            'nama' => ['required'],
            // 'kelas' => ['required','integer'],
            'nomor_telp' => ['required', 'numeric'],
            'alamat' => ['required'],
            // 'spp' => ['required','integer'],
        ]);

        try {
            // dd($request->all());
            $user = new Siswa();
            $user->nisn = $request->nisn;
            $user->nis = $request->nis;
            $user->nama = $request->nama;
            $user->id_kelas = $request->id_kelas;
            $user->nomor_telp = $request->nomor_telp;
            $user->alamat = $request->alamat;
            $user->id_spp = $request->id_spp;
            $user->save();
        } catch (\Exception $e) {
            return redirect()->back()->withErrors(['Data Siswa gagal disimpan'])->withInput();
        }
        return redirect('siswa')->with('status', 'Data Siswa berhasil di simpan.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $siswa = Siswa::find($id);
        $kelas = Kelas::all();
        $spp = Spp::all();
        return view('layouts.siswa.edit', [
            'siswa' => $siswa,
            'kelas' => $kelas,
            'spp' => $spp,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nisn' => ['required', 'numeric'],
            'nis' => ['required', 'numeric'],
            'nama' => ['required'],
            'nomor_telp' => ['required', 'numeric'],
            'alamat' => ['required'],
        ]);

        try {
            // dd($request->all());
            $user = Siswa::find($id);
            $user->nisn = $request->nisn;
            $user->nis = $request->nis;
            $user->nama = $request->nama;
            $user->id_kelas = $request->id_kelas;
            $user->nomor_telp = $request->nomor_telp;
            $user->alamat = $request->alamat;
            $user->id_spp = $request->id_spp;
            $user->save();
        } catch (\Exception $e) {
            return redirect()->back()->withErrors(['Data Siswa gagal disimpan'])->withInput();
        }
        return redirect('siswa')->with('status', 'Data Siswa berhasil di simpan.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = Siswa::find($id);
        $user->delete();
         
         return redirect()->back()->with('status','Siswa berhasil dihapus');
    }
}

resources/views/layouts/siswa/create.blade.php
@extends('adminlte::page')
@section('title', 'Halaman Tambah Siswa')
@section('content_header')
    <h1>Tambah Siswa</h1>
@stop
@section('link')
    <li class="breadcrumb-item"><a href="{{ route('siswa.index') }}">Siswa</a></li>
    <li class="breadcrumb-item active">Tambah</li>
@stop
@section('content')
    <div class="card">
        <div class="card-body">
            @if ($errors->any())
                <x-adminlte-alert theme="danger" title="Kesalahan">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </x-adminlte-alert>
            @endif
            <form method="POST" action="{{ route('siswa.store') }}">
                @csrf

                <div class="row mb-3">
                    <label for="nisn" class="col-md-4 col-form-label text-mdend">{{ __('Nisn') }}</label>
                    <div class="col-md-6">
                        <input id="nisn" type="text" class="form-control @error('nisn') is-invalid @enderror"
                            name="nisn" value="{{ old('nisn') }}" required autocomplete="nama" autofocus>
                        @error('nisn')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="nis" class="col-md-4 col-form-label text-mdend">{{ __('Nis') }}</label>
                    <div class="col-md-6">
                        <input id="nis" type="text" class="form-control @error('nis') is-invalid @enderror"
                            name="nis" value="{{ old('nis') }}" required autocomplete="nama" autofocus>
                        @error('nis')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="nama" class="col-md-4 col-form-label text-mdend">{{ __('Nama') }}</label>
                    <div class="col-md-6">
                        <input id="nama" type="text" class="form-control @error('nama') is-invalid @enderror"
                            name="nama" value="{{ old('nama') }}" required autocomplete="nama" autofocus>
                        @error('nama')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="id_kelas" class="col-md-4 col-form-label textmd-end">{{ __('Kelas') }}</label>
                    <div class="col-md-6">
                        <select id="id_kelas" class="form-control @error('id_kelas') is-invalid @enderror"
                        {{ count($kelas) == 0 ? 'disabled' : '' }} name="id_kelas" required>
                        @if (count($kelas) == 0)
                            <option>Pilihan Tidak ada</option>
                        @else
                            @foreach ($kelas as $k)
                            <option value="{{ $k->id }}"> {{ $k->kelas }}</option>
                            @endforeach
                        @endif
                            
                        </select>
                        @error('id_kelas')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                

                <div class="row mb-3">
                    <label for="nomor_telp" class="col-md-4 col-form-label text-mdend">{{ __('Nomor_Telp') }}</label>
                    <div class="col-md-6">
                        <input id="nomor_telp" type="text" class="form-control @error('nomor_telp') is-invalid @enderror"
                            name="nomor_telp" value="{{ old('nomor_telp') }}" required autofocus>
                        @error('nomor_telp')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="alamat" class="col-md-4 col-form-label textmd-end">{{ __('Alamat') }}</label>
                    <div class="col-md-6">
                        <textarea name="alamat" class="form-control @error('alamat') is-invalid @enderror">{{ old('alamat') }}</textarea>
                        @error('alamat')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="id_spp" class="col-md-4 col-form-label textmd-end">{{ __('Spp') }}</label>
                    <div class="col-md-6">
                        <select id="id_spp" class="form-control @error('id_spp') is-invalid @enderror"
                        {{ count($spp) == 0 ? 'disabled' : '' }} name="id_spp" required>
                        @if(count($spp) == 0)											
                              <option>Pilihan tidak ada</option>
                        @else				
                            @foreach ($spp as $p)
                                <option value="{{ $p->id }}">{{ 'Tahun '.$p->tahun.' - '.'Rp.'.$p->nominal }}</option>
                            @endforeach
                        @endif
                        </select>
                        @error('id_spp')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Simpan
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/layouts/siswa/edit.blade.php
@extends('adminlte::page')
@section('title', 'Halaman Ubah Siswa')
@section('content_header')
    <h1>Tambah Siswa</h1>
@stop
@section('link')
    <li class="breadcrumb-item"><a href="{{ route('siswa.index') }}">Siswa</a></li>
    <li class="breadcrumb-item active">Tambah</li>
@stop
@section('content')
    <div class="card">
        <div class="card-body">
            @if ($errors->any())
                <x-adminlte-alert theme="danger" title="Kesalahan">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </x-adminlte-alert>
            @endif
            <form method="POST" action="{{ route('siswa.update', $siswa->id ) }}">
                @csrf
                @method('PUT')

                <div class="row mb-3">
                    <label for="nisn" class="col-md-4 col-form-label text-mdend">{{ __('Nisn') }}</label>
                    <div class="col-md-6">
                        <input id="nisn" type="text" class="form-control @error('nisn') is-invalid @enderror"
                            name="nisn" value="{{ $siswa->nisn }}" required autocomplete="nama" autofocus>
                        @error('nisn')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="nis" class="col-md-4 col-form-label text-mdend">{{ __('Nis') }}</label>
                    <div class="col-md-6">
                        <input id="nis" type="text" class="form-control @error('nis') is-invalid @enderror"
                            name="nis" value="{{ $siswa->nis }}" required autocomplete="nama" autofocus>
                        @error('nis')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="nama" class="col-md-4 col-form-label text-mdend">{{ __('Nama') }}</label>
                    <div class="col-md-6">
                        <input id="nama" type="text" class="form-control @error('nama') is-invalid @enderror"
                            name="nama" value="{{ $siswa->nama }}" required autocomplete="nama" autofocus>
                        @error('nama')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="id_kelas" class="col-md-4 col-form-label textmd-end">{{ __('Kelas') }}</label>
                    <div class="col-md-6">
                        <select id="id_kelas" class="form-control @error('id_kelas') is-invalid @enderror"
                        {{ count($kelas) == 0 ? 'disabled' : '' }} name="id_kelas" required>
                        @if (count($kelas) == 0)
                            <option>Pilihan Tidak ada</option>
                        @else
                            @foreach ($kelas as $k)
                            <option value="{{ $k->id }}"> {{ $k->kelas }}</option>
                            @endforeach
                        @endif
                            
                        </select>
                        @error('id_kelas')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                

                <div class="row mb-3">
                    <label for="nomor_telp" class="col-md-4 col-form-label text-mdend">{{ __('Nomor_Telp') }}</label>
                    <div class="col-md-6">
                        <input id="nomor_telp" type="text" class="form-control @error('nomor_telp') is-invalid @enderror"
                            name="nomor_telp" value="{{ $siswa->nomor_telp }}" required autofocus>
                        @error('nomor_telp')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="alamat" class="col-md-4 col-form-label textmd-end">{{ __('Alamat') }}</label>
                    <div class="col-md-6">
                        <textarea name="alamat" class="form-control @error('alamat') is-invalid @enderror">{{ $siswa->alamat }}</textarea>
                        @error('alamat')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="id_spp" class="col-md-4 col-form-label textmd-end">{{ __('Spp') }}</label>
                    <div class="col-md-6">
                        <select id="id_spp" class="form-control @error('id_spp') is-invalid @enderror"
                        {{ count($spp) == 0 ? 'disabled' : '' }} name="id_spp" required>
                        @if(count($spp) == 0)											
                              <option>Pilihan tidak ada</option>
                        @else				
                            @foreach ($spp as $p)
                                <option value="{{ $p->id }}">{{ 'Tahun '.$p->tahun.' - '.'Rp.'.$p->nominal }}</option>
                            @endforeach
                        @endif
                        </select>
                        @error('id_spp')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Simpan
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/layouts/siswa/index.blade.php
@extends('adminlte::page')
@section('title', 'Halaman Siswa')

@section('content_header')
    <h1 class="m-0 text-dark">Siswa</h1>
@stop
@section('link')
    <li class="breadcrumb-item active">Siswa</li>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            @if (session('status'))
                <x-adminlte-alert theme="success" title="Sukses">
                    {{ session('status') }}
                </x-adminlte-alert>
            @endif
            @if ($errors->any())
                <x-adminlte-alert theme="success" title="Sukses">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </x-adminlte-alert>
            @endif
            <a href="{{ route('siswa.create') }}" class="btn btn-md btn-success mx-1 shadow"> <i
                    class="fa fa-lg fa-fw fa-plus"></i> Tambah User</a>
            <br /> <br />
            <div class="table-responsive">
                <table id="tabel_user" class="table table-striped table-hover table-condensed table-bordered">
                    <thead>
                        <tr style="background-color: darkgrey">
                            <th>No</th>
                            <th>NISN </th>
                            <th>NIS</th>
                            <th>Nama</th>
                            <th>Kelas</th>
                            <th>No Telp</th>
                            <th class="text-center" width="100">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($siswa as $s)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $s->nisn }}</td>
                                <td>{{ $s->nis }}</td>
                                <td>{{ $s->nama }}</td>
                                <td>{{ $s->kelas->kelas }}</td>
                                <td>{{ $s->nomor_telp }}</td>
                                <td>
                                    <a href="{{route('siswa.edit',$s->id)}}" class="btn btn-sn btn-primary"
                                        title="Edit"><i class="far fa-edit"></i></a>
                                        <x-adminlte-button class="btn btn-sn btn-danger"  data-toggle="modal" data-target="#hapussiswa{{$loop->iteration}}" icon="far fa-trash-alt" class="bg-danger"> </x-adminlte-button>
                                            {{-- Custom --}}
                                        <x-adminlte-modal id="hapussiswa{{$loop->iteration}}" title="Hapus Siswa" size="md" theme="danger"
                                        icon="fas fa-bell" v-centered static-backdrop scrollable>
                                        <div style="height:80px;">
                                            <form action="{{route('siswa.delete',$s->id)}}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                  Apakah anda yakin akan menghapus siswa ini?</div>
                                        <x-slot name="footerSlot">
                                            <x-adminlte-button type="submit" class="mr-auto" theme="primary" label="Hapus"/>
                                            <x-adminlte-button theme="danger" label="Batal" data-dismiss="modal"/>
                                            </form>
                                        </x-slot>
                                        </x-adminlte-modal>
                                </td>



                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>


@stop
@section('plugins.Datatables', true)
@section('js')
    <script>
        $('#tabel_siswa').DataTable();
    </script>
@stop